language: python
python:
  - "3.5"
branches:
  only:
    - source
cache: pip
install:
  - pip install -r requirements.txt --cache-dir $HOME/.cache/pip
  - git submodule update --init --recursive
script:
  - make travis
