[build]
publish = "public"
command = "./prepare.sh && $HUGO --gc --minify"

[build.environment]
GO_VERSION = "1.18"
GO_IMPORT_PATH = "github.com/higebu/higebu.com"
HUGO = "/opt/build/repo/bin/hugo"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "./prepare.sh && $HUGO --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "./prepare.sh && $HUGO --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "./prepare.sh && $HUGO --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
